// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(authenticationFFI)
import authenticationFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_authentication_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_authentication_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureAuthenticationInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol NativeClientProtocol: AnyObject, Sendable {
    
    /**
     * Get all domains as JSON array
     */
    func allDomains() throws  -> String
    
    /**
     * Start network authentication using stored credentials - returns actions to perform as JSON
     */
    func authenticate(nowMs: UInt64) throws  -> String
    
    /**
     * Authenticate with discovery service - returns actions to perform as JSON
     */
    func authenticateDiscovery(nowMs: UInt64) throws  -> String
    
    /**
     * Authenticate with specific credentials - returns actions to perform as JSON
     * This will clear all existing tokens and authenticate as a new user
     */
    func authenticateWith(credentials: NativeCredentials, nowMs: UInt64) throws  -> String
    
    /**
     * Check the current authentication state
     */
    func checkAuthState(nowMs: UInt64)  -> NativeAuthenticationState
    
    /**
     * Clear all domain accesses
     */
    func clearAllDomainAccesses() 
    
    /**
     * Clear domain access for a specific domain
     */
    func clearDomainAccess(domainId: String) 
    
    /**
     * Get the current discovery token as JSON (if available)
     */
    func discoveryToken() throws  -> String?
    
    /**
     * Get domain access information as JSON (if available)
     */
    func domainAccess(domainId: String) throws  -> String?
    
    /**
     * Get domain server information as JSON (if available)
     */
    func domainServer(domainId: String) throws  -> String?
    
    /**
     * Force re-authentication and return events as JSON
     */
    func forceReauth() throws  -> String
    
    /**
     * Request access to a domain - returns actions to perform as JSON
     */
    func getDomainAccess(domainId: String, nowMs: UInt64) throws  -> String
    
    /**
     * Handle HTTP response - returns events as JSON
     */
    func handleResponse(status: UInt16, body: String) throws  -> String
    
    /**
     * Check if client has credentials
     */
    func hasCredentials()  -> Bool
    
    /**
     * Check if client is currently authenticated
     */
    func isAuthenticated(nowMs: UInt64)  -> Bool
    
    /**
     * Get the current network token as JSON (if available)
     */
    func networkToken() throws  -> String?
    
    /**
     * Check if client requires credentials
     */
    func requiresCredentials(nowMs: UInt64)  -> Bool
    
    /**
     * Save the current state as JSON
     */
    func saveState() throws  -> String
    
    /**
     * Set or update credentials
     */
    func setCredentials(credentials: NativeCredentials) 
    
    /**
     * Switch to a different user by providing new credentials
     * This is an alias for authenticate_with() that makes the intent clearer
     */
    func switchUser(credentials: NativeCredentials, nowMs: UInt64) throws  -> String
    
    /**
     * Validate current state and return events as JSON
     */
    func validateState(nowMs: UInt64) throws  -> String
    
}
open class NativeClient: NativeClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_authentication_fn_clone_nativeclient(self.handle, $0) }
    }
    /**
     * Create a new authentication client with only configuration
     * Credentials are provided later when calling authenticate_with()
     */
public convenience init(config: NativeConfig) {
    let handle =
        try! rustCall() {
    uniffi_authentication_fn_constructor_nativeclient_new(
        FfiConverterTypeNativeConfig_lower(config),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_authentication_fn_free_nativeclient(handle, $0) }
    }

    
    /**
     * Create a client from saved state JSON
     */
public static func fromState(stateJson: String, config: NativeConfig)throws  -> NativeClient  {
    return try  FfiConverterTypeNativeClient_lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_constructor_nativeclient_from_state(
        FfiConverterString.lower(stateJson),
        FfiConverterTypeNativeConfig_lower(config),$0
    )
})
}
    

    
    /**
     * Get all domains as JSON array
     */
open func allDomains()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_all_domains(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Start network authentication using stored credentials - returns actions to perform as JSON
     */
open func authenticate(nowMs: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_authenticate(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
    /**
     * Authenticate with discovery service - returns actions to perform as JSON
     */
open func authenticateDiscovery(nowMs: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_authenticate_discovery(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
    /**
     * Authenticate with specific credentials - returns actions to perform as JSON
     * This will clear all existing tokens and authenticate as a new user
     */
open func authenticateWith(credentials: NativeCredentials, nowMs: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_authenticate_with(
            self.uniffiCloneHandle(),
        FfiConverterTypeNativeCredentials_lower(credentials),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
    /**
     * Check the current authentication state
     */
open func checkAuthState(nowMs: UInt64) -> NativeAuthenticationState  {
    return try!  FfiConverterTypeNativeAuthenticationState_lift(try! rustCall() {
    uniffi_authentication_fn_method_nativeclient_check_auth_state(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
    /**
     * Clear all domain accesses
     */
open func clearAllDomainAccesses()  {try! rustCall() {
    uniffi_authentication_fn_method_nativeclient_clear_all_domain_accesses(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Clear domain access for a specific domain
     */
open func clearDomainAccess(domainId: String)  {try! rustCall() {
    uniffi_authentication_fn_method_nativeclient_clear_domain_access(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(domainId),$0
    )
}
}
    
    /**
     * Get the current discovery token as JSON (if available)
     */
open func discoveryToken()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_discovery_token(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get domain access information as JSON (if available)
     */
open func domainAccess(domainId: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_domain_access(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(domainId),$0
    )
})
}
    
    /**
     * Get domain server information as JSON (if available)
     */
open func domainServer(domainId: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_domain_server(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(domainId),$0
    )
})
}
    
    /**
     * Force re-authentication and return events as JSON
     */
open func forceReauth()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_force_reauth(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Request access to a domain - returns actions to perform as JSON
     */
open func getDomainAccess(domainId: String, nowMs: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_get_domain_access(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(domainId),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
    /**
     * Handle HTTP response - returns events as JSON
     */
open func handleResponse(status: UInt16, body: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_handle_response(
            self.uniffiCloneHandle(),
        FfiConverterUInt16.lower(status),
        FfiConverterString.lower(body),$0
    )
})
}
    
    /**
     * Check if client has credentials
     */
open func hasCredentials() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_authentication_fn_method_nativeclient_has_credentials(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Check if client is currently authenticated
     */
open func isAuthenticated(nowMs: UInt64) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_authentication_fn_method_nativeclient_is_authenticated(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
    /**
     * Get the current network token as JSON (if available)
     */
open func networkToken()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_network_token(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Check if client requires credentials
     */
open func requiresCredentials(nowMs: UInt64) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_authentication_fn_method_nativeclient_requires_credentials(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
    /**
     * Save the current state as JSON
     */
open func saveState()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_save_state(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Set or update credentials
     */
open func setCredentials(credentials: NativeCredentials)  {try! rustCall() {
    uniffi_authentication_fn_method_nativeclient_set_credentials(
            self.uniffiCloneHandle(),
        FfiConverterTypeNativeCredentials_lower(credentials),$0
    )
}
}
    
    /**
     * Switch to a different user by providing new credentials
     * This is an alias for authenticate_with() that makes the intent clearer
     */
open func switchUser(credentials: NativeCredentials, nowMs: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_switch_user(
            self.uniffiCloneHandle(),
        FfiConverterTypeNativeCredentials_lower(credentials),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
    /**
     * Validate current state and return events as JSON
     */
open func validateState(nowMs: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAuthError_lift) {
    uniffi_authentication_fn_method_nativeclient_validate_state(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = NativeClient

    public static func lift(_ handle: UInt64) throws -> NativeClient {
        return NativeClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: NativeClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: NativeClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeClient_lift(_ handle: UInt64) throws -> NativeClient {
    return try FfiConverterTypeNativeClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeClient_lower(_ value: NativeClient) -> UInt64 {
    return FfiConverterTypeNativeClient.lower(value)
}




public struct NativeConfig: Equatable, Hashable {
    public var apiUrl: String
    public var refreshUrl: String
    public var ddsUrl: String
    public var clientId: String
    public var refreshThresholdMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(apiUrl: String, refreshUrl: String, ddsUrl: String, clientId: String, refreshThresholdMs: UInt64) {
        self.apiUrl = apiUrl
        self.refreshUrl = refreshUrl
        self.ddsUrl = ddsUrl
        self.clientId = clientId
        self.refreshThresholdMs = refreshThresholdMs
    }

    
}

#if compiler(>=6)
extension NativeConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeConfig {
        return
            try NativeConfig(
                apiUrl: FfiConverterString.read(from: &buf), 
                refreshUrl: FfiConverterString.read(from: &buf), 
                ddsUrl: FfiConverterString.read(from: &buf), 
                clientId: FfiConverterString.read(from: &buf), 
                refreshThresholdMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: NativeConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.apiUrl, into: &buf)
        FfiConverterString.write(value.refreshUrl, into: &buf)
        FfiConverterString.write(value.ddsUrl, into: &buf)
        FfiConverterString.write(value.clientId, into: &buf)
        FfiConverterUInt64.write(value.refreshThresholdMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeConfig_lift(_ buf: RustBuffer) throws -> NativeConfig {
    return try FfiConverterTypeNativeConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeConfig_lower(_ value: NativeConfig) -> RustBuffer {
    return FfiConverterTypeNativeConfig.lower(value)
}


public struct NativeDiscoveryAuth: Equatable, Hashable {
    public var token: String
    public var expiresAt: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(token: String, expiresAt: UInt64) {
        self.token = token
        self.expiresAt = expiresAt
    }

    
}

#if compiler(>=6)
extension NativeDiscoveryAuth: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeDiscoveryAuth: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeDiscoveryAuth {
        return
            try NativeDiscoveryAuth(
                token: FfiConverterString.read(from: &buf), 
                expiresAt: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: NativeDiscoveryAuth, into buf: inout [UInt8]) {
        FfiConverterString.write(value.token, into: &buf)
        FfiConverterUInt64.write(value.expiresAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeDiscoveryAuth_lift(_ buf: RustBuffer) throws -> NativeDiscoveryAuth {
    return try FfiConverterTypeNativeDiscoveryAuth.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeDiscoveryAuth_lower(_ value: NativeDiscoveryAuth) -> RustBuffer {
    return FfiConverterTypeNativeDiscoveryAuth.lower(value)
}


public struct NativeDomainAccess: Equatable, Hashable {
    public var id: String
    public var name: String
    public var organizationId: String
    public var domainServerId: String
    public var accessToken: String
    public var expiresAt: UInt64
    public var domainServer: NativeDomainServer
    public var ownerWalletAddress: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, organizationId: String, domainServerId: String, accessToken: String, expiresAt: UInt64, domainServer: NativeDomainServer, ownerWalletAddress: String) {
        self.id = id
        self.name = name
        self.organizationId = organizationId
        self.domainServerId = domainServerId
        self.accessToken = accessToken
        self.expiresAt = expiresAt
        self.domainServer = domainServer
        self.ownerWalletAddress = ownerWalletAddress
    }

    
}

#if compiler(>=6)
extension NativeDomainAccess: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeDomainAccess: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeDomainAccess {
        return
            try NativeDomainAccess(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                organizationId: FfiConverterString.read(from: &buf), 
                domainServerId: FfiConverterString.read(from: &buf), 
                accessToken: FfiConverterString.read(from: &buf), 
                expiresAt: FfiConverterUInt64.read(from: &buf), 
                domainServer: FfiConverterTypeNativeDomainServer.read(from: &buf), 
                ownerWalletAddress: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: NativeDomainAccess, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.organizationId, into: &buf)
        FfiConverterString.write(value.domainServerId, into: &buf)
        FfiConverterString.write(value.accessToken, into: &buf)
        FfiConverterUInt64.write(value.expiresAt, into: &buf)
        FfiConverterTypeNativeDomainServer.write(value.domainServer, into: &buf)
        FfiConverterString.write(value.ownerWalletAddress, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeDomainAccess_lift(_ buf: RustBuffer) throws -> NativeDomainAccess {
    return try FfiConverterTypeNativeDomainAccess.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeDomainAccess_lower(_ value: NativeDomainAccess) -> RustBuffer {
    return FfiConverterTypeNativeDomainAccess.lower(value)
}


public struct NativeDomainServer: Equatable, Hashable {
    public var id: String
    public var organizationId: String
    public var name: String
    public var url: String
    public var version: String
    public var status: String
    public var mode: String
    public var variants: [String]
    public var ip: String
    public var latitude: Double
    public var longitude: Double
    public var cloudRegion: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, organizationId: String, name: String, url: String, version: String, status: String, mode: String, variants: [String], ip: String, latitude: Double, longitude: Double, cloudRegion: String) {
        self.id = id
        self.organizationId = organizationId
        self.name = name
        self.url = url
        self.version = version
        self.status = status
        self.mode = mode
        self.variants = variants
        self.ip = ip
        self.latitude = latitude
        self.longitude = longitude
        self.cloudRegion = cloudRegion
    }

    
}

#if compiler(>=6)
extension NativeDomainServer: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeDomainServer: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeDomainServer {
        return
            try NativeDomainServer(
                id: FfiConverterString.read(from: &buf), 
                organizationId: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf), 
                version: FfiConverterString.read(from: &buf), 
                status: FfiConverterString.read(from: &buf), 
                mode: FfiConverterString.read(from: &buf), 
                variants: FfiConverterSequenceString.read(from: &buf), 
                ip: FfiConverterString.read(from: &buf), 
                latitude: FfiConverterDouble.read(from: &buf), 
                longitude: FfiConverterDouble.read(from: &buf), 
                cloudRegion: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: NativeDomainServer, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.organizationId, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.version, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterString.write(value.mode, into: &buf)
        FfiConverterSequenceString.write(value.variants, into: &buf)
        FfiConverterString.write(value.ip, into: &buf)
        FfiConverterDouble.write(value.latitude, into: &buf)
        FfiConverterDouble.write(value.longitude, into: &buf)
        FfiConverterString.write(value.cloudRegion, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeDomainServer_lift(_ buf: RustBuffer) throws -> NativeDomainServer {
    return try FfiConverterTypeNativeDomainServer.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeDomainServer_lower(_ value: NativeDomainServer) -> RustBuffer {
    return FfiConverterTypeNativeDomainServer.lower(value)
}


public struct NativeNetworkAuth: Equatable, Hashable {
    public var token: String
    public var refreshToken: String
    public var expiresAt: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(token: String, refreshToken: String, expiresAt: UInt64) {
        self.token = token
        self.refreshToken = refreshToken
        self.expiresAt = expiresAt
    }

    
}

#if compiler(>=6)
extension NativeNetworkAuth: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeNetworkAuth: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeNetworkAuth {
        return
            try NativeNetworkAuth(
                token: FfiConverterString.read(from: &buf), 
                refreshToken: FfiConverterString.read(from: &buf), 
                expiresAt: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: NativeNetworkAuth, into buf: inout [UInt8]) {
        FfiConverterString.write(value.token, into: &buf)
        FfiConverterString.write(value.refreshToken, into: &buf)
        FfiConverterUInt64.write(value.expiresAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeNetworkAuth_lift(_ buf: RustBuffer) throws -> NativeNetworkAuth {
    return try FfiConverterTypeNativeNetworkAuth.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeNetworkAuth_lower(_ value: NativeNetworkAuth) -> RustBuffer {
    return FfiConverterTypeNativeNetworkAuth.lower(value)
}


public enum AuthError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case JsonError(message: String)
    
    case InvalidState(message: String)
    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension AuthError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAuthError: FfiConverterRustBuffer {
    typealias SwiftType = AuthError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AuthError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .JsonError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .InvalidState(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AuthError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .JsonError(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .InvalidState(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthError_lift(_ buf: RustBuffer) throws -> AuthError {
    return try FfiConverterTypeAuthError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthError_lower(_ value: AuthError) -> RustBuffer {
    return FfiConverterTypeAuthError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum NativeAuthenticationState: Equatable, Hashable {
    
    case authenticated
    case needsRefresh
    case needsAuthentication
    case needsCredentials



}

#if compiler(>=6)
extension NativeAuthenticationState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeAuthenticationState: FfiConverterRustBuffer {
    typealias SwiftType = NativeAuthenticationState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeAuthenticationState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .authenticated
        
        case 2: return .needsRefresh
        
        case 3: return .needsAuthentication
        
        case 4: return .needsCredentials
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NativeAuthenticationState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .authenticated:
            writeInt(&buf, Int32(1))
        
        
        case .needsRefresh:
            writeInt(&buf, Int32(2))
        
        
        case .needsAuthentication:
            writeInt(&buf, Int32(3))
        
        
        case .needsCredentials:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeAuthenticationState_lift(_ buf: RustBuffer) throws -> NativeAuthenticationState {
    return try FfiConverterTypeNativeAuthenticationState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeAuthenticationState_lower(_ value: NativeAuthenticationState) -> RustBuffer {
    return FfiConverterTypeNativeAuthenticationState.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum NativeCredentials: Equatable, Hashable {
    
    case emailPassword(email: String, password: String
    )
    case appKey(appKey: String, appSecret: String
    )
    case opaque(token: String, refreshToken: String?, expiryMs: UInt64, refreshTokenExpiryMs: UInt64?, oidcClientId: String?
    )



}

#if compiler(>=6)
extension NativeCredentials: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeCredentials: FfiConverterRustBuffer {
    typealias SwiftType = NativeCredentials

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeCredentials {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .emailPassword(email: try FfiConverterString.read(from: &buf), password: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .appKey(appKey: try FfiConverterString.read(from: &buf), appSecret: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .opaque(token: try FfiConverterString.read(from: &buf), refreshToken: try FfiConverterOptionString.read(from: &buf), expiryMs: try FfiConverterUInt64.read(from: &buf), refreshTokenExpiryMs: try FfiConverterOptionUInt64.read(from: &buf), oidcClientId: try FfiConverterOptionString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NativeCredentials, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .emailPassword(email,password):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(email, into: &buf)
            FfiConverterString.write(password, into: &buf)
            
        
        case let .appKey(appKey,appSecret):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(appKey, into: &buf)
            FfiConverterString.write(appSecret, into: &buf)
            
        
        case let .opaque(token,refreshToken,expiryMs,refreshTokenExpiryMs,oidcClientId):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(token, into: &buf)
            FfiConverterOptionString.write(refreshToken, into: &buf)
            FfiConverterUInt64.write(expiryMs, into: &buf)
            FfiConverterOptionUInt64.write(refreshTokenExpiryMs, into: &buf)
            FfiConverterOptionString.write(oidcClientId, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeCredentials_lift(_ buf: RustBuffer) throws -> NativeCredentials {
    return try FfiConverterTypeNativeCredentials.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeCredentials_lower(_ value: NativeCredentials) -> RustBuffer {
    return FfiConverterTypeNativeCredentials.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
public func currentTimeMs() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_authentication_fn_func_current_time_ms($0
    )
})
}
public func isExpired(expiresAt: UInt64, nowMs: UInt64) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_authentication_fn_func_is_expired(
        FfiConverterUInt64.lower(expiresAt),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
public func isNearExpiry(expiresAt: UInt64, thresholdMs: UInt64, nowMs: UInt64) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_authentication_fn_func_is_near_expiry(
        FfiConverterUInt64.lower(expiresAt),
        FfiConverterUInt64.lower(thresholdMs),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_authentication_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_authentication_checksum_func_current_time_ms() != 14940) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_func_is_expired() != 34195) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_func_is_near_expiry() != 36859) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_all_domains() != 56848) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_authenticate() != 50337) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_authenticate_discovery() != 59590) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_authenticate_with() != 36277) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_check_auth_state() != 17025) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_clear_all_domain_accesses() != 34225) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_clear_domain_access() != 8527) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_discovery_token() != 9751) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_domain_access() != 43082) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_domain_server() != 13428) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_force_reauth() != 1341) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_get_domain_access() != 33295) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_handle_response() != 22379) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_has_credentials() != 8584) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_is_authenticated() != 23161) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_network_token() != 21909) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_requires_credentials() != 58306) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_save_state() != 55535) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_set_credentials() != 15982) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_switch_user() != 25808) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_method_nativeclient_validate_state() != 22770) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_constructor_nativeclient_from_state() != 52243) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_authentication_checksum_constructor_nativeclient_new() != 12846) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureAuthenticationInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all